apiVersion: v1
data:
  CONFIG_EDITOR_PW: U2hJQ3lLcUd0SlJwemtIMg==
  DATABASE_SECRET_KEY: Sm1KaGwtN3ZNcjJmU2JLUnNWT3JJWld2ZXdQTGtrcFFaUU1EcURtYUlxUTZTQXBsRHlCbmI5R1JZS2JzRDRuM0VpZHNrWTNxVmpFeFZZenU=
  DB_ROOT_PW: YjBUbDBnRW9rdTUtLVZ4S2NhbFdVUXF1MXlKMFNkQ08=
  DB_URI: cG9zdGdyZXNxbDovL21vZGVsLXJlZ2lzdHJ5LTM3LXF1YXktZGF0YWJhc2U6QlRteUpDd2ZsWXJOUE9xd0MyRXN0SWpaSXRLVWhiOHlKV05wMXdwT245ZHo1STlrbjdVRHlteHhBTjBrLWNHWlJBdFlyLTc0ZHE2Y2g3TVNAbW9kZWwtcmVnaXN0cnktcXVheS1kYXRhYmFzZTo1NDMyL21vZGVsLXJlZ2lzdHJ5LTM3LXF1YXktZGF0YWJhc2U=
  SECRET_KEY: b1ZEaW40WHRoM1dzSHVPVy1xTU9MUUZqTFNFSDlib2czb1ZrOWxKcGdTWVd0UmRzdzZRaG1YV0Q5TkhnZVlmUFlkVkJDeHNCc2pxYXBZb2U=
  SECURITY_SCANNER_V4_PSK: TTJGS1MxcFRkalJJUzBwV1N6ZFVjMFV3ZDJzeU0ybFFPWGN6UlZaWVlXRT0=
kind: Secret
metadata:
  annotations:
    quay-buildmanager-hostname: ""
    quay-operator-service-endpoint: http://quay-operator.quay.svc.cluster.local:7071
    quay-registry-hostname: model-registry.apps.ocpadm001vm002400.vodafone.com.au
  labels:
    quay-operator/quayregistry: model-registry
  name: model-registry-quay-registry-managed-secret-keys
  namespace: quay
type: Opaque